#!/bin/sh

LUXURYWATCH=""
LUXURYWATCH="${LUXURYWATCH} CARTIER"
LUXURYWATCH="${LUXURYWATCH} PANERAI"
LUXURYWATCH="${LUXURYWATCH} HUBLOT"
LUXURYWATCH="${LUXURYWATCH} BREITLING"
LUXURYWATCH="${LUXURYWATCH} IWC-SCHAFFHAUSEN"
LUXURYWATCH="${LUXURYWATCH} ZENITH"
LUXURYWATCH="${LUXURYWATCH} OMEGA"
LUXURYWATCH="${LUXURYWATCH} BLANCPAIN"
LUXURYWATCH="${LUXURYWATCH} BREGUET"
LUXURYWATCH="${LUXURYWATCH} ROLEX"
LUXURYWATCH="${LUXURYWATCH} JAEGER-LECOULTRE"
LUXURYWATCH="${LUXURYWATCH} A-LANGE-AND-SOHNE"
LUXURYWATCH="${LUXURYWATCH} AUDEMARS-PIGUET"
LUXURYWATCH="${LUXURYWATCH} VACHERON-CONSTANTIN"
LUXURYWATCH="${LUXURYWATCH} PATEK-PHILIPPE"

echo 'This is the list of Luxury Watch from FIRST-POSITION-LUXURYWATCH'
for WATCH in ${LUXURYWATCH}; do
echo ${WATCH};
done
echo ''
echo 'This is the list of all Luxury Watch which came from FIRST-POSITION-LUXURYWATCH : '
echo ${LUXURYWATCH}
echo ''
echo 'This is the name of the third Luxury Watch which came from FIRST-POSITION-LUXURYWATCH : '
echo ${LUXURYWATCH} | cut -d' ' -f3
echo ''
echo 'This is the name of the sixth Luxury Watch which came from FIRST-POSITION-LUXURYWATCH : '
echo ${LUXURYWATCH} | cut -d' ' -f6
echo ''
echo 'Just add the Luxury Watch from LUXURYWATCH'
LUXURYWATCH="${LUXURYWATCH} TUDOR"
echo ''
echo 'This the name of the fifteenth Luxury Watch whick came from FOURTH-POSITION-LUXURYWATCH :'
echo ${LUXURYWATCH} | cut -d' ' -f15
echo ''
echo 'This is the name of the sixteenth Luxury Watch which came from THIRD-POSITION-LUXURYWATCH :'
echo ${LUXURYWATCH} | cut -d' ' -f16
echo ''
echo 'Just add more the Luxury Watch from THIRD-POSITION-LUXURYWATCH...'
LUXURYWATCH="${LUXURYWATCH} PIAGET"
LUXURYWATCH="${LUXURYWATCH} CHOPARD"
echo ''
echo 'This is the name of the eighteenth Luxury Watch which came from THIRD-POSITION-LUXURYWATCH :'
echo ${LUXURYWATCH} | cut -d' ' -f18
echo ''
echo 'Just add the Luxury Watch from SECOND-POSITION-LUXURYWATCH, THIRD-POSITION-LUXURYWATCH and FOURTH-POSITION-LUXURYWATCH.'
THIRD_POSITION_LUXURYWATCH=""
THIRD_POSITION_LUXURYWATCH="${THIRD_POSITION_LUXURYWATCH} TAG-HEUER"
THIRD_POSITION_LUXURYWATCH="${THIRD_POSITION_LUXURYWATCH} BREMONT"
THIRD_POSITION_LUXURYWATCH="${THIRD_POSITION_LUXURYWATCH} F.P.-JOURNE"
THIRD_POSITION_LUXURYWATCH="${THIRD_POSITION_LUXURYWATCH} BOVET-FLEURIER"
THIRD_POSITION_LUXURYWATCH="${THIRD_POSITION_LUXURYWATCH} JAQUET-DROZ"
THIRD_POSITION_LUXURYWATCH="${THIRD_POSITION_LUXURYWATCH} GLASHUTTE"
THIRD_POSITION_LUXURYWATCH="${THIRD_POSITION_LUXURYWATCH} RICHARD-MILLE"
echo ''
echo 'This is the name of the third Luxury Watch from THIRD-POSITION-LUXURYWATCH : '
echo ${THIRD_POSITION_LUXURYWATCH} | cut -d' ' -f3
echo ''
echo 'This is the list of all Luxury Watch which came from THIRD-POSITION-LUXURYWATCH : '
echo ${LUXURYWATCH}
echo ''
echo 'This is the name of the fifth Luxury Watch from THIRD-POSITION-LUXURYWATCH :'
echo ${THIRD_POSITION_LUXURYWATCH} | cut -d' ' -f5
echo ''
echo 'This is the name of the seventh Luxury Watch from THIRD-POSITION-LUXURYWATCH :'
echo ${THIRD_POSITION_LUXURYWATCH} | cut -d' ' -f7
echo ''
echo 'This is the list of all Luxury Watch which came from THIRD-POSITION-LUXURYWATCH :'
echo ${THIRD_POSITION_LUXURYWATCH}
